### ISSUE TITLE
timeout('The write operation timed out')

### ISSUE THREAD

**Issue by neo-64** [jak119/hassio-backup-azure-blob#2]
Hi,

I can't push my backup on azure blob. Connection string and container name are ok but : 
7500dd72.tar
96845faf.tar
=== Starting copy ===
ERROR: Client-Request-ID=b97ef5a2-b25a-11eb-974c-0242ac1e2105 Retry policy did not allow for a retry: , HTTP status code=Unknown, Exception=('Connection aborted.', timeout('The write operation timed out')).
ERROR: ('Connection aborted.', timeout('The write operation timed out'))
ERROR: Client-Request-ID=b9816e04-b25a-11eb-a890-0242ac1e2105 Retry policy did not allow for a retry: , HTTP status code=Unknown, Exception=('Connection aborted.', timeout('The write operation timed out')).
ERROR: Client-Request-ID=0a4546eb-b25b-11eb-9731-0242ac1e2105 Retry policy did not allow for a retry: , HTTP status code=Unknown, Exception=('Connection aborted.', timeout('The write operation timed out')).
ERROR: Client-Request-ID=0ef4bf79-b25b-11eb-8fac-0242ac1e2105 Retry policy did not allow for a retry: , HTTP status code=Unknown, Exception=('Connection aborted.', timeout('The write operation timed out')).

I can see put blob activity so i think my configuration is ok 
![image](https://user-images.githubusercontent.com/44203748/117823162-75a72600-b26d-11eb-99b8-ab784203a6ab.png)

any idea ?

**Comment by neo-64** [comment]
I think there's a workarround with --timeout on the az command but and don't know where is the script hassio-backup-azure-blob

**Comment by jak119** [comment]
Good find on the `--timeout` flag, I'm indeed not specifying it. You can see the actual script that's getting called (it's nothing fancy) in [run.sh](https://github.com/jak119/hassio-backup-azure-blob/blob/main/run.sh). I'll take a stab at adding in a parameter to accept a timeout value sometime over the next few evenings.

**Comment by jak119** [comment]
@neo-64 As a follow up question, are you able to write to an Azure Storage Account from anywhere on the same network where HA is running? Just want to be sure there's not a firewall or ISP-level block that's preventing outbound HTTPS to the service.

**Comment by neo-64** [comment]
I copy azure blob in the same network frequently with azure explorer. I'm noob in home assistant, where i can find run.sh in my homeassistant ? I'll make some test to confirm if i can edit run.sh on my config.

Regards

**Comment by jak119** [comment]
Thought I'd fixed this, but broke when I got to my actual HA instance. Reopening to investigate.
