### ISSUE TITLE
Unable to start addon

### ISSUE THREAD

**Issue by Rygorazd** [jak119/hassio-backup-azure-blob#26]
After installation and basic configuration I'm unable to start the addon.
Only one error in log:
> s6-overlay-suexec: fatal: can only run as pid 1

**Comment by jak119** [comment]
Sorry about that, I'll have to do some testing to see what's going on. From the S6 documentation what I'm doing is still perfectly acceptable, but I wonder if there was some Home Assistant specific breaking change I missed.

**Comment by Rygorazd** [comment]
After updating to 1.1.4 worked fine. Thank you for very fast resolution

**Comment by jak119** [comment]
Glad that worked! Thanks for letting me know I broke it.
