### ISSUE TITLE
Can't copy new backup files

### ISSUE THREAD

**Issue by Rygorazd** [jak119/hassio-backup-azure-blob#35]
Hitting some isses when trying to copy new files to Azure blob:
`22:40:17] INFO: === Starting copy ===
ERROR: The specified blob already exists.
RequestId:f9301787-901e-0019-47fc-4a1a99000000
Time:2023-02-27T22:41:21.6601902Z
ErrorCode:BlobAlreadyExists
If you want to overwrite the existing one, please add --overwrite in your command.'

Backup to Azure Blob
Current version: 1.1.4

**Comment by jak119** [comment]
If you're not cleaning up your HA backups the add on (well, the Azure CLI) will just ignore the ones that have already been uploaded and throw that warning. Would your expectation be that it overwrites? If so I can explore adding an option to do that.

**Comment by Rygorazd** [comment]
Looks like they were copied after all. thanks for response, I'm guessing no need for overwriting them anyway.
